spring:
  application:
    name: store
  jwt:
    secret: ${JWT_SECRET} # environment variables are common, keep in general application.yaml
    accessTokenExpiration: 900 # 15 min ## 7200 # 2h ## 300 # 5m
    refreshTokenExpiration: 608400 # 7d
  profiles:
    active: dev
stripe:
  api:
    secret: ${STRIPE_SECRET}
  webhook:
    secret: ${STRIPE_WEBHOOK_SECRET}